### ISSUE TITLE
[Bug] App crashes when add something to the shopping list from the home menu

### ISSUE THREAD

**Issue by BluePixel4k** [estep248/PocketPlan#39]
The app crashes when I add something to the shopping list from the home menu.
It doesn't matter what I add.

Device: Google Pixel 5
OS: Android 12.1 - GrapheneOS
App version: v.1.3.5

**Comment by JakeGonder** [comment]
We already fixed that bug on the dev branch [here](https://github.com/estep248/PocketPlan/commit/5c56e27a338c0dae9e8191e26739cae7fc4cb6dc) we just did not want to push a new version live yet due to the small amount of changes, thanks for letting us know anyway, I will push the new version live in the next few days.

**Comment by JakeGonder** [comment]
The update 1.3.6 is now live in the playstore.
